app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls'), name='home'),
    path('shop/', include('immoshop.urls'), name='shop_home'),
    path('sh/', include('core.shop.urls'), name='sh_home'),
    path('cart/', include('core.cart.urls')),
    path('orders/', include('core.orders.urls')),
     # invoices
    path("custom", include("customs.urls")),
    path("invoice", include("invoices.urls")),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'config'

urlpatterns = [
    path('', include('project.urls'), name='root'),
    path('home/', include('project.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('sh/', include('shop.urls'), name='sh_home'),
    #path('cart/', include('core.cart.urls')),
    path("client/", include("customer.urls")),
    # invoices
    #path("invoice/", include("invoices.urls")),
    ## Projet Immobilier
    #path('immoshop/', include('immoshop.urls', 'immoshop'), name='immoshop'),
    ## Projet Concession Auto
    #path('carshop/', include(('autocar.urls', 'carshop'), namespace='carshop')),
    #path('orders/', include('core.orders.urls', 'orders'), namespace='orders'),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

core/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    ## path('', views.cart_detail, name='cart_detail'),
    path('', views.CartItemArticle.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add_item, name='cart_add_item'),
    path('update/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

customer/urls.py
from django.urls import path
from . import views 

app_name = 'customer'

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    ## Create
    path('create_account/', views.CustomCreate.as_view(), name='account_create'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('immoshop.urls'), name='home'),
    path('sh', include('core.shop.urls'), name='sh_home'),
    path('admin/', admin.site.urls),
    path('project/', include('project.urls')),
    path('cart/', include('core.cart.urls')),
    path('orders/', include('core.orders.urls')),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

core/cart__/models.py
from django.db import models

# Create your models here.

core/cart__/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
# cart/views.py
from typing import Any
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from .cart import Cart
from cart.forms import CartAddProductForm
from core.utils import get_product_model
from core.shop import models as sh_models
from immoshop import models as pro_models


Product_model = get_product_model()
_

def cart_add_item(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product_model, id=product_id) 
    cart.add(product=product,)
    return redirect('cart:cart_detail')

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product_model, id=product_id) 
    form = CartAddProductForm(request.POST)

    
    if form.is_valid():
        cdata = form.cleaned_data
        cart.add(product=product, quantity=cdata['quantity'], update_quantity=True)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product_model, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

class CartItemArticle(ListView): # new
    model = pro_models.ImmoProduct
    template_name = "cart/detail.html"
    #context_object_name = "cart"
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        context =  super().get_context_data(**kwargs)
        # cart
        moncart = sh_models.ShopCart.objects.get_or_create_cart(user=self.request.user)
        # items queryset
        items = sh_models.ItemArticle.objects.filter(cart=moncart)
        messages.add_message(self.request, messages.INFO, f"mes items dans panier {items}")
        
        # Ajouter le form pour chaque ligne du panier
        for item in items :
            initial_data = {'quantity': item.quantity, 'update': True}
            item.update_quantity_form = CartAddProductForm(initial=initial_data)
        context['cart'] = items
        return context

core/cart/views.py
# cart/views.py
from typing import Any
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from core.cart.cart import Cart
from core.cart.forms import CartAddProductForm
from core.utils import get_product_model
from shop import models as sh_models
from product import models as pro_models

## on charge le master models 
#product_model = get_product_model()
product_model = pro_models.Product

def cart_add_item(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(product_model, id=product_id) 
    cart.add(product=product,)
    return redirect('cart:cart_detail')

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product_model, id=product_id) 
    form = CartAddProductForm(request.POST)

    
    if form.is_valid():
        cdata = form.cleaned_data
        cart.add(product=product, quantity=cdata['quantity'], update_quantity=True)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product_model, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

class CartItemArticle(ListView): # new
    model = pro_models.Product
    template_name = "cart/detail.html"
    #context_object_name = "cart"
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        context =  super().get_context_data(**kwargs)
        # cart
        moncart = sh_models.ShopCart.objects.get_or_create_cart(user=self.request.user)
        # items queryset
        items = sh_models.ItemArticle.objects.filter(cart=moncart)
        messages.add_message(self.request, messages.INFO, f"mes items dans panier {items}")
        
        # Ajouter le form pour chaque ligne du panier
        for item in items :
            initial_data = {'quantity': item.quantity, 'update': True}
            item.update_quantity_form = CartAddProductForm(initial=initial_data)
        context['cart'] = items
        return context

core/cart__/views.py
# cart/views.py
from typing import Any
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from core.cart.cart import Cart
from core.cart.forms import CartAddProductForm
from core.utils import get_product_model
from shop import models as sh_models
from product import models as pro_models

## on charge le master models 
#product_model = get_product_model()
product_model = pro_models.Product

def cart_add_item(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(product_model, id=product_id) 
    cart.add(product=product,)
    return redirect('cart:cart_detail')

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product_model, id=product_id) 
    form = CartAddProductForm(request.POST)

    
    if form.is_valid():
        cdata = form.cleaned_data
        cart.add(product=product, quantity=cdata['quantity'], update_quantity=True)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product_model, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

class CartCartItem(ListView): # new
    model = pro_models.Product
    template_name = "cart/detail.html"
    #context_object_name = "cart"
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        context =  super().get_context_data(**kwargs)
        # cart
        moncart = sh_models.ShopCart.objects.get_or_create_cart(user=self.request.user)
        # items queryset
        items = sh_models.CartItem.objects.filter(cart=moncart)
        messages.add_message(self.request, messages.INFO, f"mes items dans panier {items}")
        
        # Ajouter le form pour chaque ligne du panier
        for item in items :
            initial_data = {'quantity': item.quantity, 'update': True}
            item.update_quantity_form = CartAddProductForm(initial=initial_data)
        context['cart'] = items
        return context

templates/cart/detail.html
{% extends 'product/base_shop.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, MAD. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.default_image_exist  %} 
                                                    {{ product.default_image.url }} 
                                                {% else %} {% static 'img/thumbnail_100x100_plan-apprt-3d.jpg' %}
                                                {% endif %}" style="height: 130px; width: 300">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-warning ">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>MAD {{ item.price }}</td>
                            <td>MAD {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>MAD {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "shop:product_shop_list" %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url "customer:account_create" %}" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}