app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls'), name='home'),
    path('shop/', include('immoshop.urls'), name='shop_home'),
    path('sh/', include('core.shop.urls'), name='sh_home'),
    path('cart/', include('core.cart.urls')),
    path('orders/', include('core.orders.urls')),
     # invoices
    path("custom", include("customs.urls")),
    path("invoice", include("invoices.urls")),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'config'

urlpatterns = [
    path('', include('project.urls'), name='root'),
    path('home/', include('project.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('sh/', include('shop.urls'), name='sh_home'),
    #path('cart/', include('core.cart.urls')),
    path("client/", include("customer.urls")),
    # invoices
    #path("invoice/", include("invoices.urls")),
    ## Projet Immobilier
    #path('immoshop/', include('immoshop.urls', 'immoshop'), name='immoshop'),
    ## Projet Concession Auto
    #path('carshop/', include(('autocar.urls', 'carshop'), namespace='carshop')),
    #path('orders/', include('core.orders.urls', 'orders'), namespace='orders'),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

core/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    ## path('', views.cart_detail, name='cart_detail'),
    path('', views.CartItemArticle.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add_item, name='cart_add_item'),
    path('update/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

customer/urls.py
from django.urls import path
from . import views 

app_name = 'customer'

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    ## Create
    path('create_account/', views.CustomCreate.as_view(), name='account_create'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('immoshop.urls'), name='home'),
    path('sh', include('core.shop.urls'), name='sh_home'),
    path('admin/', admin.site.urls),
    path('project/', include('project.urls')),
    path('cart/', include('core.cart.urls')),
    path('orders/', include('core.orders.urls')),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

immoshop/urls.py
from django.urls import path
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from weasyprint import HTML
from shop import views as shop_models 
from immoshop import api as shop_apiviews
from immoshop import api as shop_api
from immoshop import views as immo_views


app_name="immoshop"

urlpatterns = [
    #path('home/', shop_models.product_immo_list, name='home_immo_list'),
    path('', shop_models.product_home, name='home_immo_list'),
    path('home/', shop_models.product_home, name='home_immo_list'),
    path('list/', shop_models.product_home, name='product_immo_list'),
    path('cat/<slug:category_slug>/', shop_models.product_immo_list, name='product_list_by_category'),
    path('show/<int:pk>/', shop_models.ProductDetailView.as_view(), name='product_immo_detail'),
    # Devis invoice
    path('create_invoice/<int:user_id>', immo_views.InvoiceCreate.as_view(), name='invoice_create'),
    path('invoices/generate/<int:invoice_id>', immo_views.generate_pdf_invoice, name="generate_pdf",),
    ## successs
    path('success/', immo_views.success, name="success",),
    ## API 
    path('api/user/', shop_apiviews.UserApiList.as_view(), name="user_api" ), # new
    path('api/user/<int:pk>/', shop_apiviews.UserApiDetail.as_view(), name="user_api" ), # new
]

immoshop/models.py
# models.py
from typing import Any, MutableMapping
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from product import models as pro_models

class ImmoProduct(pro_models.Product):
    
    def get_images(self):
        return self.images.all()

    def get_absolute_url(self):
        return reverse("immoshop:product_immo_detail", args=[str(self.id)])

class ImmoProductImage(pro_models.ProductImage):
    pass
    
class ImmoProductSpecificationValue(pro_models.ProductSpecificationValue):
    """ The product specification value table hold each of the 
    product individal specification or bespoke features.
    """
    pass

immoshop/views.py
# Dajango Contrib
from typing import Any
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.contrib.auth.models import AnonymousUser
from django.conf import settings
from django.utils.decorators import method_decorator
from django.db import transaction   
from immoshop.forms import CustomFormSet
from customer.forms import CustomCreatForm, AccountUserCreationForm
from django.views import View




## Generic View
from django.views.generic import (
    View,
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.views import View
## local app modules
from weasyprint import HTML
from core.orders.models import OrderItem
from product import models as pro_models
from shop import models as sh_models 
from customer import models as cu_models 
from immoshop import models as immo_models
from invoices import models as devis_models
from shop.models import ShopCart
from django.urls import reverse, resolve
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from customer.forms import CustomCreatForm, AccountUserCreationForm
from core.utils import get_product_model, Dict2Obj
from core.cart__.forms import CartAddProductForm
from core.taxonomy import models as tax_models
from django.shortcuts import get_object_or_404



# product Model setting
product_model = get_product_model()

def category_list(request, categoy_slug=None ):
    category = get_object_or_404(pro_models.MPCategory, slug=categoy_slug)
    products = pro_models.ImmoProduct.objects.filter(
        category__in = pro_models.MPCategory.objects
        .get(name=categoy_slug).get_descendants(include_self=False)
    )
    context = {
            "categoy": category,
            "products": products,
            }
    return render(request, "immoshop/category_list.html", context=context)
    

def product_list(request, category_slug=None):
    category = None
    categories = pro_models.MPCategory.objects.all()
    products = pro_models.Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(pro_models.MPCategory, slug=category_slug)
        products = pro_models.Product.objects.filter(category=category)

    pro_context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, "immoshop/product_detail.html", context=pro_context)

def product_home(request, category_slug=None):
    products_list = product_model.objects.all()
    category = None
    categories = pro_models.MPCategory.objects.all()
    #
    if category_slug:
        category = get_object_or_404(pro_models.MPCategory, slug=category_slug)
    
    # ProductSpecificationValues
    for product in products_list:
        options = [] 
        psv = pro_models.ProductSpecificationValue.objects.filter(product=product)
        for spec in psv:
            attributes = {"product": spec.product.id,
                       "name": spec.specification.name,
                       "value": spec.value,
                    }
            options.append(Dict2Obj(attributes))
        ## add options
        product.options = options
    
    context = { 'products' : products_list,
                'category': category,
                'categories': categories,
                'cart_product_form' : CartAddProductForm()
               } 
    return render(request, "immoshop/home.html", context=context)

@login_required
def product_immo_list(request, category_slug=None):
    products_list = product_model.objects.all()
    category = None
    categories = pro_models.MPCategory.objects.all()
    #
    if category_slug:
        category = get_object_or_404(pro_models.MPCategory, slug=category_slug)
    
    context = { 'products' : products_list,
                'category': category,
                'categories': categories,
                'cart_product_form' : CartAddProductForm()
               } 
    return render(request, "immoshop/product_list.html", context=context)

def product_immo_detail(request, product_id, slug):
    return render(request, "immoshop/product_detail.html", context={})

class ProductDetailView(DetailView): # new
    model = immo_models.ImmoProduct
    template_name = "immoshop/product_detail.html"
    context_object_name = "product"
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        context =  super().get_context_data(**kwargs)
        # formulaire 
        cart_product_form = CartAddProductForm()
        # Récupérer les images associées à ce produit en utilisant la méthode que nous avons définie dans le modèle
        product = self.get_object()
        product_images = product.images.all()
        # les psecifications du produit 
        
        options = [] 
        psv = pro_models.ProductSpecificationValue.objects.filter(product=product)
        for spec in psv:
            attributes = {"product": spec.product.id,
                       "name": spec.specification.name,
                       "value": spec.value,
                    }
            options.append(Dict2Obj(attributes))
        ## add options
        product.options = options

        context = {
            'product':  product,
            'product_images' : product_images,
            'image' : product_images.first(),
            'cart_product_form': cart_product_form
        }
      
        return context
    
class InvoiceCreate(View):
    template_name = "immoshop/create.html"
    form_class = CustomCreatForm

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        # formulaire 
        custom_form = self.form_class()
        context = context.upoadet({
            'form': custom_form
        })
      
        return context
        
    def get(self, request, user_id):
        #
        user = User.objects.get(pk=user_id)
        form = self.form_class(initial={"user": user})
        ## 
        return render(request, self.template_name, {"form": form})
    
    def post(self, request, *args, **kwargs):
        # cart 
        cart = ShopCart(request) 
        cart_id = request.session[settings.CART_SESSION_ID]

        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            shop_cart = sh_models.ShopCart.objects.get(id=cart_id)
            items = shop_cart.item_articles.all()
            # 1- create client 
            form.instance.user = request.user
            customer  = form.save()
            
            # 2- create invoice + ItemInvoice
            devis = devis_models.Invoice(title="Mon devis test", 
                                         client = customer, 
                                         invoice_total = 100,
                                         )
            for item in items:
                devis_models.InvoiceItem.objects.create(
                    invoice = devis,
                    item = item, 
                    quantity=item.quantity,
                    rate = 12,
                    tax = 15.5, 
                    price=item.product.price,
                )
            # vider le panier 
            cart.clear()
            
            ## url = reverse('invoice-detail', kwargs={'pk' : devis.pk}) 
            #response =  redirect('invoice:invoice-detail')
            return redirect('invoice_detail', pk=devis.pk)
        else :
            user = form.instance.user
            #return redirect('invoice_create', user_id=user.pk)
            return render(request, self.template_name, {"form": form})
    
    
    
def invoice_create(request):
    """ 
    1- create client user
    2- create invoice + ItemInvoice
    3- Valider la commande ou la reservation
    """
    cart = ShopCart(request) 
    cart_id = request.session[settings.CART_SESSION_ID]
    #raise Exception(f" cart={cart}, card_id={cart_id}")
    context = {} 
    shop_cart = sh_models.ShopCart.objects.get(id=cart_id)
    items = shop_cart.item_articles.all()
    
    if request.method == 'POST':
        form = CustomCreatForm(request.POST)
        if form.is_valid():
            # 1- create client 
            customer  = form.save()
            # 2- create invoice + ItemInvoice
            devis = devis_models.Invoice(title="Mon devis test", 
                                         client = customer, 
                                         invoice_total = 100,
                                         )
            for item in items:
                devis_models.InvoiceItem.objects.create(
                    invoice = devis,
                    item = item, 
                    quantity=item.quantity,
                    rate = 12,
                    tax = 15.5, 
                    price=item.product.price,
                )
            # vider le panier 
            cart.clear()
            ## url = reverse('invoice-detail', kwargs={'pk' : devis.pk}) 
            #response =  redirect('invoice:invoice-detail')
            return redirect('invoice_detail', pk=devis.pk)
    else:
        form = CustomCreatForm()
        context = { 'items':items, 'form': form }

    return render(request, 'orders/order/create.html', context )

        
@login_required
def generate_pdf_invoice(request, invoice_id):
    """Generate PDF Invoice"""

    queryset = Invoice.objects.filter(user=request.user)
    invoice = get_object_or_404(queryset, pk=invoice_id)

    client = invoice.client
    user = invoice.user
    invoice_items = InvoiceItem.objects.filter(invoice=invoice)

    context = {
        "invoice": invoice,
        "client": client,
        "user": user,
        "invoice_items": invoice_items,

templates/immoshop/base.html
<!DOCTYPE html>
{% load i18n static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}E-sakani On-line Shop{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}"/>
       <!-- Intégration de Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400">
</head>
<body>
{% include 'immoshop/navbar.html' %}

<div class="container">
    <div class="row" style="margin-top: 6%">
         <button class="btn btn-info pull-right">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    My Shopping Order:
                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                        {{ totail_items }} item {{ totail_items|pluralize }}, DH {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
         </button>
    </div>
</div>

<div class="container-fluid" > 
    {% if messages %}
        <ul id="messages">
            {% for message in messages %}
            <li id="message_{{ forloop.counter }}">
            <a href="#" onclick="$('#message_{{ forloop.counter }}').fadeOut(); return false;"><small>{% trans "clear" %}</small></a> {{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
     
    {% block content %}{% endblock %}
</div>

{# Global javascript #}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- Intégration de Bootstrap JS (si nécessaire) -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

 {# Override this in templates to add extra javascript #}
 <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>-->

 {% block extra_js %}{% endblock %}
</body>
</html>

templates/immoshop/created.html
{% extends "immoshop/base_shop.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
                <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/immoshop/detail_immoshop.html
{% extends "immoshop/base_shop.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}


{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, MAD. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.default_image_exist  %} 
                                                    {{ product.default_image.url }} 
                                                {% else %} {% static 'img/thumbnail_100x100_plan-apprt-3d.jpg' %}
                                                {% endif %}" style="height: 130px; width: 300">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-warning ">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>MAD {{ item.price }}</td>
                            <td>MAD {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>MAD {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "immoshop:product_immo_list" %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url "immoshop:account_create" %}" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}

templates/immoshop/home.html
{% extends "immoshop/base_home.html" %}
{% load static i18n  %}
 <main id="main" role="main">

{% block content %}
{% if not product %}

    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="shop-category">
                    <h1 class="my-4 lead">B-Shop</h1>
                    <div class="list-group">
                        <a href="#" class="list-group-item active">Category 1</a>
                        {% for cat in categories %}
                            <a href="#" class="list-group-item"> {{ cat }}</a>
                        {% endfor %}

                   </div>
                </div>
                <div class="recommended">
                    <h2 class="my-4 lead">Recommended</h2>
                    <div class="list-group">
                        <a href="#" class="list-group-item">Recently Viewed
                            <i class="fa fa-chevron-right"></i>
                        </a>
                        <a href="#" class="list-group-item">Best Sellers
                            <i class="fa fa-chevron-right"></i>
                        </a>
                        <a href="#" class="list-group-item">Best Of Phones
                            <i class="fa fa-chevron-right"></i>
                        </a>
                        <a href="#" class="list-group-item">Top Picks In Fashion
                            <i class="fa fa-chevron-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 pt-lg-5">
                <div id="carousel-slide" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-slide" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-slide" data-slide-to="1"></li>
                        <li data-target="#carousel-slide" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'img/prestigia_900x350_01.jpg' %}" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'img/prestigia_900x350_02.jpg' %}" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'img/prestigia_900x350_03.jpg' %}" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carousel-slide" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carousel-slide" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <div class="row pt-lg-5">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    {% if product.default_image_exist %}
                                    <img class="card-img-top" src="{% static  product.default_image %}" alt="Item 1">
                                    {% endif %}
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'immoshop:product_immo_detail' product.pk %}">
                                            {{ product.name | slice:"0:30" }}</a>
                                    </h4>
                                    <h5> <p class="text-center">{{ product.price }} Euro</p> </h5>

                                    <p class="text-center">{{ product.price }} Euro</p>
                                    <p class="card-text">{{ product.description }} </p>
                                </div>
                                <div class="card-footer">
                                    <div class="col-xs-12 col-md-6">
                                        <a href="{% url 'cart:cart_add_item' product.id %}" class="btn btn-warning btn-lg"> Ajouter au panier </a> 
                                    </div>
                                    <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <a href="#" class="btn btn-primary scrollUp">
        <i class="fa fa-arrow-circle-o-up"></i>
    </a>
{% endif %}
{% endblock %}
</main>

templates/immoshop/images.html
{% extends 'shop/base.html' %}
{% load i18n static %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">
        <div class="col-md-6 text-right">
            <img class="rounded-lg rounded-3 img-fluid" src="{{ image.image.url }}" alt="{{ product.name }}" style="height: 370px; width: auto">
        </div>
      </div><!-- /.row -->
    </div><!-- /.container -->
{% endblock %}