app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls'), name='home'),
    path('shop/', include('immoshop.urls'), name='shop_home'),
    path('sh/', include('core.shop.urls'), name='sh_home'),
    path('cart/', include('core.cart.urls')),
    path('orders/', include('core.orders.urls')),
     # invoices
    path("custom", include("customs.urls")),
    path("invoice", include("invoices.urls")),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'config'

urlpatterns = [
    path('', include('project.urls'), name='root'),
    path('home/', include('project.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('sh/', include('shop.urls'), name='sh_home'),
    #path('cart/', include('core.cart.urls')),
    path("client/", include("customer.urls")),
    # invoices
    #path("invoice/", include("invoices.urls")),
    ## Projet Immobilier
    #path('immoshop/', include('immoshop.urls', 'immoshop'), name='immoshop'),
    ## Projet Concession Auto
    #path('carshop/', include(('autocar.urls', 'carshop'), namespace='carshop')),
    #path('orders/', include('core.orders.urls', 'orders'), namespace='orders'),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('immoshop.urls'), name='home'),
    path('sh', include('core.shop.urls'), name='sh_home'),
    path('admin/', admin.site.urls),
    path('project/', include('project.urls')),
    path('cart/', include('core.cart.urls')),
    path('orders/', include('core.orders.urls')),
    path('mfu/', include("core.mfilesupload.urls")),
] 
# ... the rest of your URLconf goes here ...
## add static 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
## add static 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# add debug_toolbar 
if settings.DEBUG :
    import debug_toolbar
    urlpatterns += path('__debug__', include(debug_toolbar.urls) ),
 

project/urls.py
from django.urls import path
from project import views

app_name="project"

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project_list'),
    path('<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
]

shop/urls.py
from django.urls import path
from shop import views 

app_name="shop"

urlpatterns = [
    #path('cat/<slug:category_slug>/', views.product_shop_list, name='product_list_by_category'),
    path('show/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('add/<int:product_id>/', views.cart_add_one_item, name='cart_add_item'),
]

project/models.py
from datetime import datetime
from django.utils import timezone
from django.db import models
from django.urls import reverse, resolve
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from core.base_product import models as base_models
from polymorphic.models import PolymorphicModel, PolymorphicManager
from mptt.models import MPTTModel, TreeForeignKey
from core.profile.models import Societe
from core.taxonomy.models import TaggedItem, MPCategory
# from mapwidgets.widgets import GooglePointField
##from django.contrib.gis.db import models as gmodels
from core import deferred

# Create your models here.
class Partenaire(models.Model):
    tiers_id    = models.CharField(max_length=3)
    tiers_name  = models.CharField(max_length=100)
    tiers_type  = models.CharField(max_length=1, choices=(('C', 'Client'), ('F', 'Fornisseur')), default='F')
    created     = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    # Listed below are the mandatory fields for a generic relation
    content_type    = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id       = models.PositiveIntegerField()
    content_object  = GenericForeignKey('content_type', 'object_id')


    def __str__(self):
        return "tiers=%s id=%s" % (self.tiers_type , self.tiers_id)

class Project(base_models.BaseProject):
    societe = models.ForeignKey(Societe, on_delete=models.CASCADE)
    category = models.ForeignKey(MPCategory, related_name='projetcs', null=True, blank=True, on_delete=models.CASCADE)
    partenaire  = GenericRelation(Partenaire, null=True, blank=True) # clients ou fournisseurs
    documents   = GenericRelation('taxonomy.GDocument',  null=True, blank=True) #  les documents rattachées
    lon = models.FloatField(null=True, blank=True) # longitude
    lat = models.FloatField(null=True, blank=True) # latitude
    #location = gmodels.PointField(null=True, blank=True)


class ProjectImage(base_models.BaseImage) :
    project = models.ForeignKey(Project, related_name='images', null=True, blank=True, on_delete=models.CASCADE)

project/forms.py
from mapwidgets.widgets import GooglePointFieldWidget, GoogleStaticOverlayMapWidget
from django.contrib.gis.forms import PointField
from mapwidgets.widgets import MapboxPointFieldWidget

class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ("coordinates", "city_hall")
        widgets = {
            'coordinates': GooglePointFieldWidget,
            'city_hall': GoogleStaticOverlayMapWidget,
        }



class HouseCreateForm(forms.ModelForm):
    location_has_default = PointField(widget=MapboxPointFieldWidget)

    class Meta:
        model = House
        fields = ("name", "location", "location_has_default")
        widgets = {
            "location": GooglePointFieldWidget,
        }

project/views.py
from typing import Any
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import ListView, DetailView
from project import models as proj_models
from django.conf import settings

class ProjectListView(ListView):
    template_name = "project/project_list.html"
    model = proj_models.Project
    context_object_name = "projects"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:

        context =  super().get_context_data(**kwargs)
        context.update ( 
            {
                'app_name' : settings.APP_LABEL.lower(),
                #'app_name' : "carshop",
            })
        return context
      

class ProjectDetailView(DetailView):
    template_name = "project/project_detail.html"
    model = proj_models.Project
    context_object_name = "project"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:

        context =  super().get_context_data(**kwargs)

        project = self.get_object()
        produits = project.product_set.all()
        project_images = project.images.all()
        ## raise(Exception(project_images))
    
        context.update ( 
            {
            'project_images' : project_images,
            'products' : produits,
            'image' : project_images.first(),
            'app_name' : "carshop",
            })
      
        return context
    
    

templates/project/base.html
<!DOCTYPE html>
{% load static i18n  %}
<html lang="en">
<head>
    <title>My Shop - Beautiful Shop Homepage</title>
    <!-- Required meta tags always come first -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="My Shop - Beautiful Shop Homepage , E-Commerce ">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" lang="en" content="Simple Bootstrap 4 Shop template , Responsive and Modern HTML5 Template made from bootstrap 4.">
    <meta name="keywords" lang="en" content="E-Commerce template, bootstrap 4 template,bootstrap 4 Shop template, responsive bootstrap 4 template, bootstrap 4, bootstraping, bootstrap4, oribitthemes">
    <meta name="robots" content="index, follow">
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
    <!--Font Awesome-->
    <link rel="stylesheet" href="{% static 'dist/font-awesome/css/font-awesome.min.css' %}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    <!--[if IE]>
      <link href="https://cdn.jsdelivr.net/gh/coliff/bootstrap-ie8/css/bootstrap-ie9.min.css" rel="stylesheet">
      <script src="https://cdn.jsdelivr.net/g/html5shiv@3.7.3"></script>
    <![endif]-->
    <!--[if lt IE 9]>
      <link href="https://cdn.jsdelivr.net/gh/coliff/bootstrap-ie8/css/bootstrap-ie8.min.css" rel="stylesheet">
    <![endif]-->
</head>

<body class="bg-info">
    <div class="loader"></div>
    <header id="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#" id="header-logo">
                    <img src="{% static 'img/logo-ecommerce.jpg' %%}" 
                        class="img-circle img-rounded" width="100"
                        alt="Orbit Themes">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#top-navigation" aria-controls="top-navigation"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="top-navigation">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-success ml-lg-3" href="#">
                                <i class="fa fa-cart-plus"></i> Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary ml-lg-3" href="#">
                                <i class="fa fa-sign-in"></i> Sign In</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
   

    <div class="container-fluid" > 
        {% block header %}
            {% include "project/includes/header.html" %}
        {% endblock %}
        <!-- Message erreur -->
        {% if messages %}
            <ul id="messages">
                {% for message in messages %}
                    <li id="message_{{ forloop.counter }}">
                        <a href="#" onclick="$('#message_{{ forloop.counter }}').fadeOut(); return false;">
                        <small>{% trans "clear" %}</small></a> {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <!-- Content -->
        {% block content %}{% endblock %}
    </div>
    <!-- Footer -->
    <footer id="footer">
        <p class="copyright">Made with
            <i class="fa fa-heart"></i> By
            <a target="_blank" title="Orbit Themes" href="http://www.atlass.fr:91">Atlasofts</a> &copy;
            <span id="currentYear"></span> All Rights Reserved.
        </p>
        <div class="social">
            <a traget="_blank" href="https://facebook.com/orbitthemes" title="facebook">
                <i class="fa fa-facebook"></i>
            </a>
            <a traget="_blank" href="https://twitter.com/orbitthemes" title="twitter">
                <i class="fa fa-twitter"></i>
            </a>
            <a traget="_blank" href="https://plus.google.com/+orbitthemes" title="Google+" target="_blank">
                <i class="fa fa-google-plus"></i>
            </a>
            <a traget="_blank" href="https://github.com/orbitthemes" title="github" target="_blank">
                <i class="fa fa-github"></i>
            </a>
            <a traget="_blank" href="https://www.behance.net/orbitthemes" title="Behance" target="_blank">
                <i class="fa fa-behance"></i>
            </a>
            <a traget="_blank" href="https://dribbble.com/orbitthemes" title="Dribbble" target="_blank">
                <i class="fa fa-dribbble"></i>
            </a>
            <a traget="_blank" href="https://www.pinterest.com/orbitThemes/" title="Pinterest" target="_blank">
                <i class="fa fa-pinterest"></i>
            </a>
            <a traget="_blank" href="https://www.reddit.com/user/orbitthemes" title="Reddit" target="_blank">
                <i class="fa fa-reddit"></i>
            </a>
            <a traget="_blank" href="https://orbitthemes.com/blog/" title="RSS" target="_blank">
                <i class="fa fa-rss"></i>
            </a>
        </div>
    </footer>
    <!-- jQuery first, then Bootstrap JS. -->
    <script src="{% static 'dist/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'dist/popper/popper.min.js' %}" integrity=""></script>
    <script src="{% static 'dist/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
</body>

</html>

templates/project/project_detail.html
{% extends "./base.html" %}
{% load i18n static %}
<!--  load mapwidgets  -->

{% block header %} {% endblock %} 
<!-- Content -->

{% block content %}
<div class="container bg-light">
    <h3 class="mb-4">Projects and Products</h3>
    <div class="breadcrumb"> <h2 class="text-center"> {{ project.title }} </h2> </div>
    
    <div class="row mt-3">
        <div class="col-md-12">
            <img src="{{ project.default_image.url }}" class="img-fluid" width="80%%"
                alt="{{ project.title }}">
        </div>
        <div class="col-md-6">
            <h2> <a href="#"> {{ project.title }}  </a> </h2>
            <p>{{ project.description }}</p>
             <div class="map-container">
                <!--  product.location|gis_map:"map_widgets/google.html"  -->
            </div>
        </div>
    </div>
    <hr/>
    <!-- les produits du projet -->
    
    <div class="row">
        {% for product in products %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        {% with url_name='project'|add:":project_detail" %}
                            <a href="{% url  url_name product.pk  %}"> 
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.description }}</p>
                                <p class="card-text"><strong>Price: </strong>${{ product.price }}</p>
                                {% if product.default_image %}
                                    <img class="card-img-top img-fluid" src="{{ product.default_image.url }}" alt="{{ product.name }}">
                                {% endif %}
                            </a>
                        {% endwith %}
                        <a href="{% url 'shop:cart_add_item' product.id %}" class="btn btn-primary mt-3">Add to Cart</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/project/project_list.html
{% extends "./base.html" %}
{% load i18n static %}

{% block content %}

<div class="container bg-light">
    <h2> Liste des projets </h2> 
    <div class="row pt-lg-5">
        {% for project in projects %}
            <div class="col-lg-6 col-md-6 mb-4">
                <div class="card h-100">
                    {% with url_name='project'|add:":project_detail" %}
                    <a href="{% url url_name  project.pk %}">
                        {% if project.default_image %}
                            <img class="card-img-top rounded-lg img-fluid mx-auto d-block" src="{{ project.default_image.url }}" alt="{{ project.default_image.url }}" style="height: 200px; width: 600px;">
                        {% endif %}
                    </a>
                    {% endwith %} 
                    <div class="card-body">
                        <h4 class="card-title">
                    {% with url_name='project'|add:":project_detail" %}
                            <a href="{% url url_name project.pk %}">
                                {{ project.title | slice:"0:30" }}
                            </a>
                    {% endwith %}
                        </h4>
                        <h5><p class="text-left">Prix à partir de : {{ project.price }} Euro</p></h5>
                        <p class="card-text">Description : {{ project.description | slice:"0:250" }}</p>
                        {% for spec in project.options %}  
                            <p class="card-text">{{ spec.name }} : {{ spec.value }}</p>
                        {% endfor %}
                    </div>
                    <div class="card-footer">
                        <div class="col-xs-12 col-md-6">
                            <a href="{% url 'project:project_detail' project.id %}" class="btn btn-warning btn-lg">Voir les détails</a> 
                        </div>
                        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
    